"""
Django settings for electrohire project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5+o88sis_b0!*x)=qjcd(7jp)byp!w8c4^10pfye^&=3oi%trv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 'daphne' must be the FIRST app in the list -- Channels' install
    # docs rely on it being loaded before django.contrib.staticfiles so
    # it can transparently replace `runserver` with an ASGI-capable
    # server. Without this, `manage.py runserver` still speaks WSGI
    # only and every WebSocket handshake to /ws/... 404s.
    'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',

    'users',
    'providers',
    'categories',
    'contacts',
    'ratings',
    'reports',
    'bookings',  # Day 11, Dev 2 — Provider Booking System
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'electrohire.urls'

AUTH_USER_MODEL = 'users.User'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",   # Vite-এর Default Port
    "http://localhost:3000",
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Dev 2, Day 5: project-level templates/ dir so templates/admin/index.html
        # (dashboard stats) overrides django.contrib.admin's own admin/index.html.
        # The filesystem loader (which reads DIRS) runs before the app_directories
        # loader, so this wins even though 'django.contrib.admin' is listed before
        # 'core' in INSTALLED_APPS.
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'electrohire.wsgi.application'

# Real-time chat entry point (electrohire/asgi.py) -- routes plain
# HTTP to the same Django app as WSGI, and WebSocket connections to
# contacts/routing.py's ChatConsumer. `daphne` (INSTALLED_APPS, above)
# is what makes `manage.py runserver` actually serve this instead of
# WSGI_APPLICATION during local dev.
ASGI_APPLICATION = 'electrohire.asgi.application'

# ── Channel layer (Channels' pub/sub backbone for real-time chat) ──
# InMemoryChannelLayer needs zero setup and is fine for local dev and
# a single-process deployment, but it does NOT work across multiple
# processes/machines: a message broadcast on one worker never reaches
# a socket held open by another. Set REDIS_URL in production (most
# hosts inject this automatically once you attach a Redis instance) to
# switch to a real shared channel layer -- nothing else in the code
# needs to change either way.
REDIS_URL = os.environ.get('REDIS_URL')

if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# `manage.py test` creates many users per test (create_user hashes a real
# password every time). PBKDF2 is intentionally slow for security, which
# just wastes time in tests — swap to a fast hasher ONLY when the test
# runner is active. Dev/production always keep Django's default (secure)
# hasher since sys.argv never contains "test" outside `manage.py test`.
if 'test' in sys.argv:
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# JWT Config
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# REST Framework Config
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Day 10, Dev 1: normalizes framework-raised errors (invalid/expired
    # JWT, missing auth header, wrong HTTP method, DRF's own 404/403,
    # throttling, ...) into the same {"status": "error", "message": "..."}
    # shape every hand-written view already returns via
    # core.response.error_response — see core/exceptions.py's docstring
    # for the bug this fixes.
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
}

# Media Files (Photo Upload-এর জন্য)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ── OTP config (Day 2, Dev 1) ─────────────────────────────────────
OTP_LENGTH = 6
OTP_EXPIRY_MINUTES = 5

# ── Email — console backend in dev, prints the OTP straight to the
#    terminal running `runserver`. Switch to SMTP once you have real
#    credentials (production only). ──
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

DEFAULT_FROM_EMAIL = 'noreply@electrohire.com'