# Generated by Django 6.0.7 on 2026-07-28 07:24

import users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('provider', 'Provider'), ('admin', 'Admin')], default='user', max_length=20),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['email', 'is_used'], name='users_otp_email_9b592c_idx'),
        ),
    ]
